accounts/urls.py
from django.urls import path

from accounts.views import login_view, sign_up_view, logout_view

urlpatterns = [
    path("accounts/login/", login_view, name="login"),
    path("accounts/sign-up/", sign_up_view, name="sign-up"),
    path("accounts/logout/", logout_view, name="logout"),
]

app_name = "accounts"

club/urls.py
from django.urls import path

from club.views import index, SportListView, SportDetailView, SportUpdateView, SportCreateView, SportDeleteView, \
    TrainerListView, TrainerDetailView, TrainerUpdateView, TrainerCreateView, TrainerDeleteView, SportsClubListView, \
    SportsClubDetailView, SportsClubCreateView, SportsClubUpdateView, SportsClubDeleteView, WorkoutListView, \
    toggle_assign_to_workout, WorkoutUpdateView, WorkoutCreateView, workout_delete

urlpatterns = [
    path("", index, name="index"),
    path("sports/", SportListView.as_view(), name="sport-list"),
    path("sports/<int:pk>/", SportDetailView.as_view(), name="sport-detail"),
    path("sports/create", SportCreateView.as_view(), name="sport-create"),
    path("sports/<int:pk>/update", SportUpdateView.as_view(), name="sport-update"),
    path("sports/<int:pk>/delete", SportDeleteView.as_view(), name="sport-delete"),
    path("trainers/", TrainerListView.as_view(), name="trainer-list"),
    path("trainers/<int:pk>/", TrainerDetailView.as_view(), name="trainer-detail"),
    path("trainers/sign-up", TrainerCreateView.as_view(), name="sign-up"),
    path("trainers/<int:pk>/update", TrainerUpdateView.as_view(), name="trainer-update"),
    path("trainers/<int:pk>/delete", TrainerDeleteView.as_view(), name="trainer-delete"),
    path("sports-clubs/", SportsClubListView.as_view(), name="sports-club-list"),
    path("sports-clubs/<int:pk>/", SportsClubDetailView.as_view(), name="sports-club-detail"),
    path("sports-clubs/create", SportsClubCreateView.as_view(), name="sports-club-create"),
    path("sports-clubs/<int:pk>/update", SportsClubUpdateView.as_view(), name="sports-club-update"),
    path("sports-clubs/<int:pk>/delete", SportsClubDeleteView.as_view(), name="sports-club-delete"),
    path("workouts/", WorkoutListView.as_view(), name="workout-list"),
    path("workouts/<int:pk>/toggle-assign/", toggle_assign_to_workout, name="toggle-workout-assign"),
    path("workouts/<int:pk>/update", WorkoutUpdateView.as_view(), name="workout-update"),
    path("workouts/create", WorkoutCreateView.as_view(), name="workout-create"),
    path("workouts/<int:pk>/delete", workout_delete, name="workout-delete"),
]

app_name = "club"

sports_club_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("club.urls", namespace="club")),
    path("", include("accounts.urls", namespace="accounts")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, SignUpForm


def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg})


def sign_up_view(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'User created - please <a href="/login">login</a>.'
            success = True
        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "accounts/sign_up.html", {"form": form, "msg": msg, "success": success})


def logout_view(request):
    logout(request)
    return redirect("/")

templates/accounts/login.html
 {% extends "base.html" %}

{% block title %} Sign IN {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} sign-in-illustration {% endblock body_class %}

{% block content %}

  <div class="page-header-login">
  <div class="position-absolute fixed-top border-radius-2xl ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block me-n4" style="background-image: url(https://appsrv1-147a1.kxcdn.com/soft-ui-design-v1.0.1/img/ivancik.jpg); background-size: cover;">
    </div>
      <div class="container py-5">
        <div class="row">
          <div class="col-lg-5 d-flex justify-content-center flex-column" style="position: absolute;
  top: 50%;
  left: 40%;
  -ms-transform: translate(-40%, -50%);
  transform: translate(-40%, -50%);">
            <div class="card card-body d-flex justify-content-center shadow-lg p-5 blur align-items-center">
              <h3 class="text-center">Sign In</h3>
                <p class="mb-0">
                  {% if msg %}
                      {{ msg | safe }}
                  {% else %}
                      Add your credentials
                  {% endif %}
                </p>
              <div class="card-body">

                <form method="post" action="" role="form">

                  {% csrf_token %}

                  <div class="mb-3">
                    {{ form.username }}
                  </div>
                  <div class="mb-3">
                    {{ form.password }}
                  </div>
                  <div class="text-center">
                    <button type="submit" name="login" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                      Sign in
                    </button>
                    <input type="hidden" name="next" value="{{ next }}">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="../../static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/accounts/sign_up.html
{% extends "base.html" %}



{% block content %}
  <section>
    <div class="container py-4 mt-6">
      <div class="row">
        <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
          <div class="card d-flex justify-content-center p-4 shadow-lg">
            <div class="text-center">
              <h1>{{ object|yesno:"Update,Create" }} Trainer</h1>
              <div class="card card-plain">
            <form role="form" method="post" enctype="multipart/form-data" autocomplete="off">
              {% csrf_token %}
              <span class="text-error"> {{ form.experience.errors }}</span>
              <span class="text-error">{{ form.password1.errors }}</span>
              <span class="text-error">{{ form.password2.errors }}</span>
              <span class="text-error"> {{ form.non_field_errors }}</span>
              <div class="card-body pb-2">
                <div class="row justify-content-center">
                  <div class="col-md-4">
                  <label>First Name</label>
                  <div class="input-group mb-4">
                    {{ form.first_name }}
                  </div>
                </div>
                <div class="col-md-4 ps-2">
                  <label>Last Name</label>
                  <div class="input-group">
                    {{ form.last_name }}
                  </div>
                </div>
                </div>
                <div class="row justify-content-center">
                  <div class="col-md-4">
                    <label>Password</label>
                  <div class="input-group mb-4">
                    {{ form.password1 }}
                  </div>
                  </div>

                  <div class="col-md-4 ps-2">
                    <label>Repeat password</label>
                  <div class="input-group">
                    {{ form.password2 }}
                  </div>
                  </div>
                </div>
                <div class="row justify-content-center">
                  <div class="col-md-4">
                  <label>Username</label>
                  <div class="input-group">
                    {{ form.username }}
                  </div>
                  </div>
                  <div class="form-group col-md-4 ps-2">
                  <label>Choose the sports club</label>
                  {{ form.sports_club }}
                </div>
                </div>
                <div class="row justify-content-center">
                  <div class="col-md-6">
                  <label>Email</label>
                  <div class="input-group">
                    {{ form.email }}
                  </div>
                  </div>
                  <div class="form-group col-md-2 ps-2">
                  <label>Experience</label>
                  {{ form.experience }}
                </div>
                </div>
                  <div class="row justify-content-center">
                    <div class="col-md-4">
                      <label>Provide your photo</label>
                      {{ form.trainer_avatar }}
                    </div>
                    <div class="col-md-4 ps-2">
                      <label>Sport</label>
                      <div class="input-group">
                        {{ form.sport }}
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12 justify-content-center">
                    <input type="submit" value="Submit" class="btn bg-gradient-primary mt-3 mb-0">
                    <a class="btn bg-gradient-danger mt-3 mb-0" href="{% url "club:index" %}">Cancel</a>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
{% endblock %}