accounts/urls.py
from django.urls import path

from accounts.views import login_view, sign_up_view, logout_view

urlpatterns = [
    path("accounts/login/", login_view, name="login"),
    path("accounts/sign-up/", sign_up_view, name="sign-up"),
    path("accounts/logout/", logout_view, name="logout"),
]

app_name = "accounts"

club/urls.py
from django.urls import path

from club.views import index, SportListView, SportDetailView, SportUpdateView, SportCreateView, SportDeleteView, \
    TrainerListView, TrainerDetailView, TrainerUpdateView, TrainerCreateView, TrainerDeleteView, SportsClubListView, \
    SportsClubDetailView, SportsClubCreateView, SportsClubUpdateView, SportsClubDeleteView, WorkoutListView, \
    toggle_assign_to_workout, WorkoutUpdateView, WorkoutCreateView, workout_delete

urlpatterns = [
    path("", index, name="index"),
    path("sports/", SportListView.as_view(), name="sport-list"),
    path("sports/<int:pk>/", SportDetailView.as_view(), name="sport-detail"),
    path("sports/create", SportCreateView.as_view(), name="sport-create"),
    path("sports/<int:pk>/update", SportUpdateView.as_view(), name="sport-update"),
    path("sports/<int:pk>/delete", SportDeleteView.as_view(), name="sport-delete"),
    path("trainers/", TrainerListView.as_view(), name="trainer-list"),
    path("trainers/<int:pk>/", TrainerDetailView.as_view(), name="trainer-detail"),
    path("trainers/sign-up", TrainerCreateView.as_view(), name="sign-up"),
    path("trainers/<int:pk>/update", TrainerUpdateView.as_view(), name="trainer-update"),
    path("trainers/<int:pk>/delete", TrainerDeleteView.as_view(), name="trainer-delete"),
    path("sports-clubs/", SportsClubListView.as_view(), name="sports-club-list"),
    path("sports-clubs/<int:pk>/", SportsClubDetailView.as_view(), name="sports-club-detail"),
    path("sports-clubs/create", SportsClubCreateView.as_view(), name="sports-club-create"),
    path("sports-clubs/<int:pk>/update", SportsClubUpdateView.as_view(), name="sports-club-update"),
    path("sports-clubs/<int:pk>/delete", SportsClubDeleteView.as_view(), name="sports-club-delete"),
    path("workouts/", WorkoutListView.as_view(), name="workout-list"),
    path("workouts/<int:pk>/toggle-assign/", toggle_assign_to_workout, name="toggle-workout-assign"),
    path("workouts/<int:pk>/update", WorkoutUpdateView.as_view(), name="workout-update"),
    path("workouts/create", WorkoutCreateView.as_view(), name="workout-create"),
    path("workouts/<int:pk>/delete", workout_delete, name="workout-delete"),
]

app_name = "club"

sports_club_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("club.urls", namespace="club")),
    path("", include("accounts.urls", namespace="accounts")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/navigation.html
{% load static %}
<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" data-placement="bottom">
              Sports Club Service
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "club:sport-list" %}" class="nav-link cursor-pointer">
                    <img src="{% static "assets/img/dumbbell_navigation.png" %}" style="width: 20px; height: 20px">
                    Sports
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "club:trainer-list" %}" class="nav-link cursor-pointer">
                    <img src="{% static "assets/img/trainer.png" %}" style="width: 20px; height: 20px">
                    Trainers
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "club:sports-club-list" %}" class="nav-link cursor-pointer">
                    <img src="{% static "assets/img/building.png" %}" style="width: 20px; height: 20px">
                    Sports Clubs
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "club:workout-list" %}" class="nav-link cursor-pointer">
                    <img src="{% static "assets/img/appointment.png" %}" style="width: 20px; height: 20px">
                    Workouts
                  </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url "accounts:logout" %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <img class="avatar rounded-circle" style="height: 38px; width: 38px; object-fit:cover;" alt="Image placeholder" src="{{ user.trainer_avatar.url }}">
                  <a href="{% url "club:trainer-detail" pk=user.id %}" class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">{{ user.get_username }}</a>
                </li>
              {% else %}
              <li class="nav-item my-auto ms-3 ms-lg-auto">
                <a href="{% url "accounts:login" %}" class="btn btn-sm bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Login</a>
              </li>
              {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if is_paginated %}
  <section class="pt-0 pb-4">
    <div class="container">
      <div class="row justify-space-between py-2">
        <div class="col-lg-4 mx-auto">
          <ul class="pagination pagination-primary justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </a>
              </li>
            {% else %}
              <li class="page-item">
                <a href="?page= {{ page_obj.number}}" class="page-link">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </a>
              </li>
            {% endif %}
            <li class="page-item active">
              <span class="page-link" style="width: 144px">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
            </li>
            {% if page_obj.has_next %}
              <li class="page-item">
                <a href="?page= {{ page_obj.next_page_number }}" class="page-link">
                  <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                </a>
              </li>
            {% else %}
              <li class="page-item">
                <a href="?page= {{ page_obj.number}}" class="page-link">
                  <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endif %}