club/urls.py
from django.urls import path

from club.views import index, SportListView, SportDetailView, SportUpdateView, SportCreateView, SportDeleteView, \
    TrainerListView, TrainerDetailView, TrainerUpdateView, TrainerCreateView, TrainerDeleteView, SportsClubListView, \
    SportsClubDetailView, SportsClubCreateView, SportsClubUpdateView, SportsClubDeleteView, WorkoutListView, \
    toggle_assign_to_workout, WorkoutUpdateView, WorkoutCreateView, workout_delete

urlpatterns = [
    path("", index, name="index"),
    path("sports/", SportListView.as_view(), name="sport-list"),
    path("sports/<int:pk>/", SportDetailView.as_view(), name="sport-detail"),
    path("sports/create", SportCreateView.as_view(), name="sport-create"),
    path("sports/<int:pk>/update", SportUpdateView.as_view(), name="sport-update"),
    path("sports/<int:pk>/delete", SportDeleteView.as_view(), name="sport-delete"),
    path("trainers/", TrainerListView.as_view(), name="trainer-list"),
    path("trainers/<int:pk>/", TrainerDetailView.as_view(), name="trainer-detail"),
    path("trainers/sign-up", TrainerCreateView.as_view(), name="sign-up"),
    path("trainers/<int:pk>/update", TrainerUpdateView.as_view(), name="trainer-update"),
    path("trainers/<int:pk>/delete", TrainerDeleteView.as_view(), name="trainer-delete"),
    path("sports-clubs/", SportsClubListView.as_view(), name="sports-club-list"),
    path("sports-clubs/<int:pk>/", SportsClubDetailView.as_view(), name="sports-club-detail"),
    path("sports-clubs/create", SportsClubCreateView.as_view(), name="sports-club-create"),
    path("sports-clubs/<int:pk>/update", SportsClubUpdateView.as_view(), name="sports-club-update"),
    path("sports-clubs/<int:pk>/delete", SportsClubDeleteView.as_view(), name="sports-club-delete"),
    path("workouts/", WorkoutListView.as_view(), name="workout-list"),
    path("workouts/<int:pk>/toggle-assign/", toggle_assign_to_workout, name="toggle-workout-assign"),
    path("workouts/<int:pk>/update", WorkoutUpdateView.as_view(), name="workout-update"),
    path("workouts/create", WorkoutCreateView.as_view(), name="workout-create"),
    path("workouts/<int:pk>/delete", workout_delete, name="workout-delete"),
]

app_name = "club"

sports_club_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("club.urls", namespace="club")),
    path("", include("accounts.urls", namespace="accounts")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

club/models.py
import os
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

import datetime


def photo_path(instance, filename):
    base_filename, file_extension = os.path.splitext(filename)
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"
    random_string = ''.join((random.choice(chars)) for _ in range(10))
    return "{directory}{basename}{randomstring}{ext}".format(
        directory=instance.directory,
        basename=base_filename,
        randomstring=random_string,
        ext=file_extension
    )


class Sport(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(null=True, blank=True)
    sport_avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to=photo_path,
        default="default.png"
    )
    directory = "sport_avatars/"

    def __str__(self):
        return self.name


class SportsClub(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    swimming_pool = models.BooleanField()
    sports_club_avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to=photo_path,
        default="default.png"
    )
    directory = "sports_club_avatars/"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["name"],
                name="unique_club"
            )
        ]

    def __str__(self):
        return self.name


class Trainer(AbstractUser):
    sports_club = models.ForeignKey(
        SportsClub,
        on_delete=models.SET_NULL,
        null=True,
        related_name="trainers"
    )
    sport = models.ForeignKey(
        Sport,
        on_delete=models.SET_NULL,
        related_name="trainers",
        null=True
    )
    trainer_avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to=photo_path,
        default="default.png"
    )
    directory = "trainer_avatars/"
    experience = models.IntegerField(null=True)

    class Meta:
        verbose_name = "trainer"
        verbose_name_plural = "trainers"

    def __str__(self):
        return (f"{self.first_name} {self.last_name} | "
                f"{self.sport.name} | {self.sports_club.name}")


class Workout(models.Model):
    HOUR_CHOICES = [(datetime.time(hour=x), '{:02d}:00'.format(x)) for x in range(6, 24)]
    WEEKDAY_CHOICES = (
        ("Mon", "Monday"),
        ("Tue", "Tuesday"),
        ("Wed", "Wednesday"),
        ("Thu", "Thursday"),
        ("Fri", "Friday"),
        ("Sat", "Saturday"),
        ("Sun", "Sunday"),
    )

    sport = models.ForeignKey(
        Sport,
        on_delete=models.SET_NULL,
        related_name="workouts",
        null=True
    )
    weekday = models.CharField(max_length=3, choices=WEEKDAY_CHOICES)
    beginning_time = models.TimeField(choices=HOUR_CHOICES)
    ending_time = models.TimeField(choices=HOUR_CHOICES)
    trainer = models.ManyToManyField(Trainer, related_name="workouts")

    class Meta:
        ordering = ["sport"]

club/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from club.forms import SportForm, TrainerCreateForm, TrainerUpdateForm, SportsClubForm, WorkoutForm, SportSearchForm, \
    TrainerSearchForm, SportsClubSearchForm, WorkoutSearchForm
from club.models import Trainer, SportsClub, Sport, Workout


def index(request):
    """View function for the home page of the site."""

    num_trainers = Trainer.objects.count()
    num_sports_clubs = SportsClub.objects.count()
    num_sports = Sport.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_trainers": num_trainers,
        "num_sports_clubs": num_sports_clubs,
        "num_sports": num_sports,
        "num_visits": num_visits + 1,
    }

    return render(request, "club/index.html", context=context)


class SportListView(LoginRequiredMixin, generic.ListView):
    model = Sport
    paginate_by = 8
    queryset = Sport.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        name = self.request.GET.get("name", "")

        context = super(SportListView, self).get_context_data(**kwargs)
        context["search_form"] = SportSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = SportSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class SportDetailView(LoginRequiredMixin, generic.DetailView):
    model = Sport
    queryset = Sport.objects.all().prefetch_related("trainers", "workouts")


class SportCreateView(LoginRequiredMixin, generic.CreateView):
    model = Sport
    form_class = SportForm
    success_url = reverse_lazy("club:sport-list")


class SportUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Sport
    form_class = SportForm
    success_url = reverse_lazy("club:sport-list")


class SportDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Sport
    success_url = reverse_lazy("club:sport-list")


class TrainerListView(LoginRequiredMixin, generic.ListView):
    model = Trainer
    queryset = Trainer.objects.select_related("sport").order_by("id")
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        name = self.request.GET.get("name", "")

        context = super(TrainerListView, self).get_context_data(**kwargs)
        context["search_form"] = TrainerSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = TrainerSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                first_name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class TrainerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Trainer
    queryset = Trainer.objects.select_related("sport", "sports_club")


class TrainerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Trainer
    form_class = TrainerCreateForm
    template_name = "accounts/sign_up.html"
    success_url = reverse_lazy("club:trainer-list")


class TrainerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Trainer
    form_class = TrainerUpdateForm
    template_name = "club/trainer_update_form.html"
    success_url = reverse_lazy("club:trainer-list")


class TrainerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Trainer
    success_url = reverse_lazy("club:trainer-list")


class SportsClubListView(LoginRequiredMixin, generic.ListView):
    model = SportsClub
    template_name = "club/sports_club_list.html"
    context_object_name = "sports_club_list"
    paginate_by = 8
    queryset = SportsClub.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        name = self.request.GET.get("name", "")

        context = super(SportsClubListView, self).get_context_data(**kwargs)
        context["search_form"] = SportsClubSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = SportsClubSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class SportsClubDetailView(LoginRequiredMixin, generic.DetailView):
    model = SportsClub
    queryset = SportsClub.objects.all().prefetch_related("trainers")
    template_name = "club/sports_club_detail.html"
    context_object_name = "sports_club"


class SportsClubCreateView(LoginRequiredMixin, generic.CreateView):
    model = SportsClub
    form_class = SportsClubForm
    template_name = "club/sports_club_form.html"
    success_url = reverse_lazy("club:sports-club-list")


class SportsClubUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = SportsClub
    form_class = SportsClubForm
    template_name = "club/sports_club_form.html"
    success_url = reverse_lazy("club:sports-club-list")


class SportsClubDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = SportsClub
    template_name = "club/sports_club_confirm_delete.html"
    context_object_name = "sports_club"
    success_url = reverse_lazy("club:sports-club-list")


class WorkoutListView(LoginRequiredMixin, generic.ListView):
    model = Workout
    paginate_by = 5
    queryset = Workout.objects.select_related("sport")

    def get_context_data(self, *, object_list=None, **kwargs):
        name = self.request.GET.get("name", "")

        context = super(WorkoutListView, self).get_context_data(**kwargs)
        context["search_form"] = WorkoutSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = WorkoutSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                sport__name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class WorkoutUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Workout
    form_class = WorkoutForm
    success_url = reverse_lazy("club:workout-list")


class WorkoutCreateView(LoginRequiredMixin, generic.CreateView):
    model = Workout
    form_class = WorkoutForm
    success_url = reverse_lazy("club:workout-list")


@login_required
def workout_delete(request, pk):
    Workout.objects.filter(id=pk).delete()
    return HttpResponseRedirect(reverse_lazy("club:workout-list"))


@login_required
def toggle_assign_to_workout(request, pk):
    trainer = Trainer.objects.get(id=request.user.id)
    workout = Workout.objects.get(id=pk)
    if workout in trainer.workouts.all():
        trainer.workouts.remove(pk)
    else:
        trainer.workouts.add(pk)
    if not workout.trainer.all():
        workout.delete()
    return HttpResponseRedirect(reverse_lazy("club:workout-list"))

templates/club/sport_confirm_delete.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}
  <div style="margin-left: 6rem; margin-top: 7rem">
    <h1>Are you sure you want to delete this sport?</h1>
  <form method="post" action="">
    {% csrf_token %}
    <div class="">
      <input class="btn bg-gradient-danger" type="submit" value="Yes, delete">
      <a class="btn bg-gradient-secondary" href="{% url "club:sport-detail" pk=sport.id %}">Cancel</a>
    </div>
  </form>
  </div>
    <section class="position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row py-5">
            <h1 class="mb-6">{{ sport.name }} Details</h1>
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2" style="height: 200px; width: 200px; object-fit:cover;" src="{{ sport.sport_avatar.url }}">
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ sport.name }}</h4>
                <div class="d-block">
                  <a href="{% url "club:sport-update" pk=sport.id %}" type="button" class="btn bg-gradient-warning w-auto mb-0">Update</a>
                  <a href="{% url "club:sport-delete" pk=sport.id %}" class="btn bg-gradient-danger w-auto mb-0">Delete</a>
                </div>
              </div>
              <div class="row mb-4">
                <div class="col-auto">
                  <span class="h6">{{ sport.trainers.count }}</span>
                  <span>Trainer{{ sport.trainers.count|pluralize }}</span>
                </div>
                <div class="col-auto">
                  <span class="h6">{{ sport.workouts.count }}</span>
                  <span>Workout{{ sport.workouts.count|pluralize }}</span>
                </div>
              </div>
              <p class="text-lg mb-0">
                {% if sport.description %}
                  {{ sport.description }}
                {% else %}
                  Sport description is not provided yet.
                {% endif %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/club/sport_detail.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}

  <section class="py-sm-7 py-5 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row py-lg-7 py-5">
            <h1 class="mb-6">{{ sport.name }} Details</h1>
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2" style="height: 200px; width: 200px; object-fit:cover;" src="{{ sport.sport_avatar.url }}">
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ sport.name }}</h4>
                <div class="d-block">
                  <a href="{% url "club:sport-update" pk=sport.id %}" type="button" class="btn bg-gradient-warning w-auto mb-0">Update</a>
                  <a href="{% url "club:sport-delete" pk=sport.id %}" class="btn bg-gradient-danger w-auto mb-0">Delete</a>
                </div>
              </div>
              <div class="row mb-4">
                <div class="col-auto">
                  <span class="h6">{{ sport.trainers.count }}</span>
                  <span>Trainer{{ sport.trainers.count|pluralize }}</span>
                </div>
                <div class="col-auto">
                  <span class="h6">{{ sport.workouts.count }}</span>
                  <span>Workout{{ sport.workouts.count|pluralize }}</span>
                </div>
              </div>
              <p class="text-lg mb-0">
                {% if sport.description %}
                  {{ sport.description }}
                {% else %}
                  Sport description is not provided yet.
                {% endif %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/club/sport_list.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}

  {% if sport_list %}
    <section class="py-3">
    <div class="container pt-7">
      <div class="row">
        <div>
          <h3>
            Sport List
            <a class="btn bg-gradient-primary float-end" href="{% url "club:sport-create" %}">Create</a>
              <form action="" method="get" class="form-inline">
                {{ search_form }}
                <button class="btn bg-gradient-primary my-auto" type="submit">
                    <i class="fa fa-search"></i>
                </button>
              </form>
          </h3>
        </div>
      </div>
    <div class="row">
      {% for sport in sport_list %}
          <div class="col-lg-3 col-sm-6">
            <div class="card card-plain card-blog">
              <div class="card-image border-radius-lg position-relative">
                <a href="{% url "club:sport-detail" pk=sport.id %}">
                  <img class="border-radius-lg move-on-hover shadow" src="{{ sport.sport_avatar.url }}" style="height: 300px; width: 300px; object-fit:cover;">
                </a>
              </div>
              <div class="card-body px-0">
                <h5>
                  {{ sport.name }}
                </h5>
                <a href="{% url "club:sport-detail" pk=sport.id %}" class="text-info icon-move-right">Read More
                  <i class="fas fa-arrow-right text-sm"></i>
                </a>
              </div>
            </div>
          </div>
      {% endfor %}
       </div>
     </div>
  </section>
  {% else %}
    <section class="py-3">
    <div class="container pt-7">
      <div class="row">
        <div>
          <h3>
            Sport List
            <a class="btn bg-gradient-primary float-end" href="{% url "club:sport-create" %}">Create</a>
            <form action="" method="get" class="form-inline">
                {{ search_form }}
                <button class="btn bg-gradient-primary my-auto" type="submit">
                    <i class="fa fa-search"></i>
                </button>
              </form>
          </h3>
          <h3 class="text-muted">Ooops... No sports found</h3>
        </div>
      </div>
    </div>
    </section>
  {% endif %}
{% endblock %}

templates/club/sports_club_detail.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}

  <section class="py-sm-7 py-5 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row py-lg-7 py-5">
            <h1 class="mb-6">Sports Club Details</h1>
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2" style="height: 200px; width: 200px; object-fit:cover;" src="{{ sports_club.sports_club_avatar.url }}">
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ sports_club.name }}</h4>
                <div class="d-block">
                  <a href="{% url "club:sports-club-update" pk=sports_club.id %}" type="button" class="btn bg-gradient-warning w-auto mb-0">Update</a>
                  <a href="{% url "club:sports-club-delete" pk=sports_club.id %}" class="btn bg-gradient-danger w-auto mb-0">Delete</a>
                </div>
              </div>
              <div class="row mb-4">
                <div class="col-auto">
                  <span class="h6">{{ sports_club.trainers.count }}</span>
                  <span>Trainer{{ sports_club.trainers.count|pluralize }}</span>
                </div>
              </div>
              <p class="text-lg mb-0">
                Swimming pool:
                {% if sports_club.swimming_pool %}
                  <img src="../../static/assets/img/correct.png" title="correct icons" style="width: 20px; height: 20px">
                {% else %}
                  <img src="../../static/assets/img/remove.png" title="delete icons" style="width: 20px; height: 20px">
                {% endif %}
                <br>
                City: {{ sports_club.city }}
                <br>
                Address: {{ sports_club.address }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/club/trainer_detail.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}

  <section class="py-sm-7 py-5 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row py-lg-7 py-5">
            <h1 class="mb-6">Trainer Details</h1>
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2" style="height: 200px; width: 200px; object-fit:cover;" src="{{ trainer.trainer_avatar.url }}">
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ trainer.first_name }} {{ trainer.last_name }}</h4>
                <div class="d-block">
                  <a href="{% url "club:trainer-update" pk=trainer.id %}" type="button" class="btn bg-gradient-warning w-auto mb-0">Update</a>
                  <a href="{% url "club:trainer-delete" pk=trainer.id %}" class="btn bg-gradient-danger w-auto mb-0">Delete</a>
                </div>
              </div>
              <div class="row mb-4">
                <div class="col-auto">
                  <span class="h6">{{ trainer.workouts.count }}</span>
                  <span>Workout{{ trainer.workouts.count|pluralize }}</span>
                </div>
              </div>
              <p class="text-lg mb-0">
                Sports club: {{ trainer.sports_club.name }}
                <br>
                Sport: {{ trainer.sport.name }}
                <br>
                Experience: {{ trainer.experience }} year{{ trainer.experience|pluralize }}
                <br>
                Username: {{ trainer.username }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/club/trainer_list.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}
  {% if trainer_list %}
    <section class="py-3">
    <div class="container pt-7">
      <div class="row">
        <div>
          <h3>
            Trainer List
            <a class="btn bg-gradient-primary float-end" href="{% url "club:sign-up" %}">Create</a>
            <form action="" method="get" class="form-inline">
              {{ search_form }}
              <button class="btn bg-gradient-primary my-auto" type="submit">
                  <i class="fa fa-search"></i>
              </button>
            </form>
          </h3>
        </div>
      </div>
    <div class="row">
      {% for trainer in trainer_list %}
          <div class="col-lg-3 col-sm-6">
            <div class="card card-plain card-blog">
              <div class="card-image border-radius-lg position-relative">
                <a href="{% url "club:trainer-detail" pk=trainer.id %}">
                  <img class="border-radius-lg move-on-hover shadow" src="{{ trainer.trainer_avatar.url }}" style="height: 300px; width: 300px; object-fit:cover;">
                </a>
              </div>
              <div class="card-body px-0">
                <h5>
                  {{ trainer.first_name }}
                  {{ trainer.last_name }}
                </h5>
                <p>
                  Sport: {{ trainer.sport.name }}
                  <br>
                  Experience: {{ trainer.experience }} year{{ trainer.experience|pluralize }}
                </p>
                <a href="{% url "club:trainer-detail" pk=trainer.id %}" class="text-info icon-move-right">Read More
                  <i class="fas fa-arrow-right text-sm"></i>
                </a>
              </div>
            </div>
          </div>
      {% endfor %}
       </div>
     </div>
  </section>
  {% else %}
    <h1>There are no trainers</h1>
  {% endif %}
{% endblock %}

templates/club/workout_list.html
{% extends "base.html" %}

{% block body_class %} bg-gray-100 {% endblock body_class %}

{% block content %}
  <div class="py-3 pt-7 text-center">
    <h1>Workout Schedule
    </h1>
    <a href="{% url "club:workout-create" %}" class="btn bg-gradient-primary m-2">Create</a>
  </div>
  <div class="card card-body border-0 shadow table-wrapper table-responsive" style="margin: 0 150px 50px 150px">
    <form action="" method="get" class="form-inline">
      {{ search_form }}
      <button class="btn bg-gradient-primary my-auto" type="submit">
          <i class="fa fa-search"></i>
      </button>
    </form>
      <table class="table table-hover">
          <thead>
              <tr>
                  <th class="border-gray-200 text-center">№</th>
                  <th class="border-gray-200 text-center">Sport</th>
                  <th class="border-gray-200 text-center">Weekday</th>
                  <th class="border-gray-200 text-center">Beginning</th>
                  <th class="border-gray-200 text-center">Ending</th>
                  <th class="border-gray-200 text-center">Assign</th>
                  <th class="border-gray-200 text-center">Update</th>
                  <th class="border-gray-200 text-center">Delete</th>
              </tr>
          </thead>
          <tbody>
              <!-- Item -->
                {% for workout in workout_list %}
                  <tr>
                    <td class="text-center align-middle">
                      {{ workout.id }}
                    </td>
                    <td class="text-center align-middle">
                      {{ workout.sport.name }}
                    </td>
                    <td class="text-center align-middle">
                      {{ workout.weekday }}
                    </td>
                    <td class="text-center align-middle">
                      {{ workout.beginning_time }}
                    </td>
                    <td class="text-center align-middle">
                      {{ workout.ending_time }}
                    </td>
                    <td class="text-center align-middle">
                      {% if user.sports_club.id != workout.trainer.first.sports_club.id %}
                        Not your club
                      {% elif user.sport == workout.sport and workout not in user.workouts.all %}
                        <a href="{% url 'club:toggle-workout-assign' pk=workout.id %}" class="btn btn-success link-to-page">
                          Assign me for this workout
                        </a>
                      {% elif user.sport == workout.sport and workout in user.workouts.all %}
                        <a href="{% url 'club:toggle-workout-assign' pk=workout.id %}" class="btn btn-danger link-to-page">
                          Delete me from this workout
                        </a>
                      {% else %}
                        Not your specialty
                      {% endif %}
                    </td>
                    <td class="text-center align-middle">
                      <a href="{% url "club:workout-update" pk=workout.id %}" class="btn bg-gradient-primary">Update</a>
                    </td>
                    <td class="text-center align-middle">
                      <a href="{% url "club:workout-delete" pk=workout.id %}" class="btn bg-gradient-secondary">Delete</a>
                    </td>
                  </tr>
                {% endfor %}
          </tbody>
      </table>
  </div>
{% endblock %}